lxd.lo: /home/lozza/php_inbuilt/lxd/ext/lxd.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/lxd.c -o lxd.lo 
kernel/main.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /home/lozza/php_inbuilt/lxd/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/kernel/exit.c -o kernel/exit.lo 
lxd/endpoint.lo: /home/lozza/php_inbuilt/lxd/ext/lxd/endpoint.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/lxd/endpoint.zep.c -o lxd/endpoint.lo 
lxd/client.lo: /home/lozza/php_inbuilt/lxd/ext/lxd/client.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/lxd/client.zep.c -o lxd/client.lo 
lxd/endpoints/certificates.lo: /home/lozza/php_inbuilt/lxd/ext/lxd/endpoints/certificates.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/lxd/endpoints/certificates.zep.c -o lxd/endpoints/certificates.lo 
lxd/endpoints/host.lo: /home/lozza/php_inbuilt/lxd/ext/lxd/endpoints/host.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/lxd/endpoints/host.zep.c -o lxd/endpoints/host.lo 
lxd/lib/certificate.lo: /home/lozza/php_inbuilt/lxd/ext/lxd/lib/certificate.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/lxd/lib/certificate.zep.c -o lxd/lib/certificate.lo 
lxd/lib/curl.lo: /home/lozza/php_inbuilt/lxd/ext/lxd/lib/curl.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/lozza/php_inbuilt/lxd/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/lozza/php_inbuilt/lxd/ext/lxd/lib/curl.zep.c -o lxd/lib/curl.lo 
$(phplibdir)/lxd.la: ./lxd.la
	$(LIBTOOL) --mode=install cp ./lxd.la $(phplibdir)

./lxd.la: $(shared_objects_lxd) $(LXD_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_lxd) $(LXD_SHARED_LIBADD)

